[build]
  command = "npm run build"
  publish = "build"

[context.production]
  environment = { NODE_VERSION = "18.x" }

[context.production.environment]
  REACT_APP_API_URL = "https://sb1-rstfa8-5adeee18270e.herokuapp.com"

[context.staging.environment]
  REACT_APP_API_URL = "https://sb1-rstfa8-5adeee18270e.herokuapp.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data: blob:; connect-src 'self' https: wss: https://sb1-rstfa8-5adeee18270e.herokuapp.com;"
